In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df= pd.read_csv('fraudTrain.csv')

In [4]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [5]:
df.shape

(1296675, 23)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [7]:
df.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [8]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [13]:
df = df.drop(columns=['Unnamed: 0'])

In [14]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0

In [15]:
df=df.drop(columns=['first','last'])

In [16]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0

In [17]:
df['dob']=pd.to_datetime(df['dob'])

In [18]:
from datetime import datetime
current_date=datetime.now()
df['age']=(current_date-df['dob']).dt.days//365

In [19]:
df=df.drop(columns=['dob'])

In [20]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,age
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,38
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,47

In [21]:
#HAVERSINE FORMULA :for calulating real distances on earth.nearby area ->less fraud. suspicious abnormal location-> more fraud
import numpy as np

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km

    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

df['distance_km'] = haversine(
    df['lat'], df['long'],
    df['merch_lat'], df['merch_long']
)

In [22]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,street,city,state,zip,...,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,age,distance_km
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,...,-81.1781,3495,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,38,78.597568
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,...,-118.2105,149,Special educational needs teacher,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,47,30.212176

In [23]:
#for calculating speed
df= df.sort_values(by=['cc_num','unix_time'])
df['time_diff'] = df.groupby('cc_num')['unix_time'].diff()  #current time-previous time
df['dist_diff'] = df.groupby('cc_num')['distance_km'].diff() #current distance-previous distance
df['speed'] = df['dist_diff'] / (df['time_diff'] / 3600)

In [24]:
df = df.drop(columns=['lat', 'long', 'merch_lat', 'merch_long', 'street'])

In [25]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,trans_num,unix_time,is_fraud,age,distance_km,time_diff,dist_diff,speed
1017,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,Fort Washakie,WY,82514,1645,Information systems manager,98e3dcf98101146a577f85a34e58feec,1325422035,0,40,127.606239,NaN,NaN,NaN
2724,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,Fort Washakie,WY,82514,1645,Information systems manager,498120fc45d277f7c88e3dba79c33865,1325493897,0,40,110.308921,71862.0,-17.297318,-0.866527

In [26]:
df['speed']=df['speed'].fillna(0)
df['time_diff']=df['time_diff'].fillna(0)
df['dist_diff']=df['dist_diff'].fillna(0)

In [27]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,trans_num,unix_time,is_fraud,age,distance_km,time_diff,dist_diff,speed
1017,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,Fort Washakie,WY,82514,1645,Information systems manager,98e3dcf98101146a577f85a34e58feec,1325422035,0,40,127.606239,0.0,0.000000,0.000000
2724,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,Fort Washakie,WY,82514,1645,Information systems manager,498120fc45d277f7c88e3dba79c33865,1325493897,0,40,110.308921,71862.0,-17.297318,-0.866527

In [28]:
df['speed'] = df['speed'].replace([np.inf, -np.inf], 0)   #if time_dii=0 i.e crash or infinity

In [29]:
df['speed'] = df['speed'].abs()

In [30]:
df['dist_diff'] = df['dist_diff'].abs()

In [31]:
df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,trans_num,unix_time,is_fraud,age,distance_km,time_diff,dist_diff,speed
1017,2019-01-01 12:47:15,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,Fort Washakie,WY,82514,1645,Information systems manager,98e3dcf98101146a577f85a34e58feec,1325422035,0,40,127.606239,0.0,0.000000,0.000000
2724,2019-01-02 08:44:57,60416207185,fraud_Berge LLC,gas_transport,52.94,F,Fort Washakie,WY,82514,1645,Information systems manager,498120fc45d277f7c88e3dba79c33865,1325493897,0,40,110.308921,71862.0,17.297318,0.866527
2726,2019-01-02 08:47:36,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,Fort Washakie,WY,82514,1645,Information systems manager,95f514bb993151347c7acdf8505c3d62,1325494056,0,40,21.787261,159.0,88.521660,2004.264001
2882,2019-01-02 12:38:14,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,Fort Washakie,WY,82514,1645,Information systems manager,4f0c1a14e0aa7eb56a490780ef9268c5,1325507894,0,40,87.204215,13838.0,65.416954,17.018430
2907,2019-01-02 13:10:46,60416207185,fraud_Beier and Sons,home,27.18,F,Fort Washakie,WY,82514,1645,Information systems manager,3b2ebd3af508afba959640893e1e82bc,1325509846,0,40,74.212965,1952.0,12.991250,23.959272

In [32]:
#extracting day,month,year from trans_date_trans_time
df['trans_date_trans_time']=pd.to_datetime(df['trans_date_trans_time'])
df['year']=df['trans_date_trans_time'].dt.year
df['month']=df['trans_date_trans_time'].dt.month
df['day']=df['trans_date_trans_time'].dt.day
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
df = df.drop(columns=['trans_date_trans_time', 'unix_time'])

In [33]:
df.head()

,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,...,age,distance_km,time_diff,dist_diff,speed,year,month,day,day_of_week,is_weekend
1017,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,F,Fort Washakie,WY,82514,1645,Information systems manager,...,40,127.606239,0.0,0.000000,0.000000,2019,1,1,1,0
2724,60416207185,fraud_Berge LLC,gas_transport,52.94,F,Fort Washakie,WY,82514,1645,Information systems manager,...,40,110.308921,71862.0,17.297318,0.866527,2019,1,2,2,0
2726,60416207185,fraud_Luettgen PLC,gas_transport,82.08,F,Fort Washakie,WY,82514,1645,Information systems manager,...,40,21.787261,159.0,88.521660,2004.264001,2019,1,2,2,0
2882,60416207185,fraud_Daugherty LLC,kids_pets,34.79,F,Fort Washakie,WY,82514,1645,Information systems manager,...,40,87.204215,13838.0,65.416954,17.018430,2019,1,2,2,0
2907,60416207185,fraud_Beier and Sons,home,27.18,F,Fort Washakie,WY,82514,1645,Information systems manager,...,40,74.212965,1952.0,12.991250,23.959272,2019,1,2,2,0

In [34]:
#checking the gender column and using label encoding
df['gender'].value_counts()
df['gender']=df['gender'].map({'M':0,'F':1})

In [35]:
df.head()

,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,...,age,distance_km,time_diff,dist_diff,speed,year,month,day,day_of_week,is_weekend
1017,60416207185,"fraud_Jones, Sawayn and Romaguera",misc_net,7.27,1,Fort Washakie,WY,82514,1645,Information systems manager,...,40,127.606239,0.0,0.000000,0.000000,2019,1,1,1,0
2724,60416207185,fraud_Berge LLC,gas_transport,52.94,1,Fort Washakie,WY,82514,1645,Information systems manager,...,40,110.308921,71862.0,17.297318,0.866527,2019,1,2,2,0
2726,60416207185,fraud_Luettgen PLC,gas_transport,82.08,1,Fort Washakie,WY,82514,1645,Information systems manager,...,40,21.787261,159.0,88.521660,2004.264001,2019,1,2,2,0
2882,60416207185,fraud_Daugherty LLC,kids_pets,34.79,1,Fort Washakie,WY,82514,1645,Information systems manager,...,40,87.204215,13838.0,65.416954,17.018430,2019,1,2,2,0
2907,60416207185,fraud_Beier and Sons,home,27.18,1,Fort Washakie,WY,82514,1645,Information systems manager,...,40,74.212965,1952.0,12.991250,23.959272,2019,1,2,2,0

In [36]:
df['category'].value_counts()

category
gas_transport     131659
grocery_pos       123638
home              123115
shopping_pos      116672
kids_pets         113035
shopping_net       97543
entertainment      94014
food_dining        91461
personal_care      90758
health_fitness     85879
misc_pos           79655
misc_net           63287
grocery_net        45452
travel             40507
Name: count, dtype: int64

In [37]:
df = pd.get_dummies(df, columns=['category'], drop_first=True)

In [38]:
df.head()

,cc_num,merchant,amt,gender,city,state,zip,city_pop,job,trans_num,...,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
1017,60416207185,"fraud_Jones, Sawayn and Romaguera",7.27,1,Fort Washakie,WY,82514,1645,Information systems manager,98e3dcf98101146a577f85a34e58feec,...,False,False,False,False,True,False,False,False,False,False
2724,60416207185,fraud_Berge LLC,52.94,1,Fort Washakie,WY,82514,1645,Information systems manager,498120fc45d277f7c88e3dba79c33865,...,False,False,False,False,False,False,False,False,False,False
2726,60416207185,fraud_Luettgen PLC,82.08,1,Fort Washakie,WY,82514,1645,Information systems manager,95f514bb993151347c7acdf8505c3d62,...,False,False,False,False,False,False,False,False,False,False
2882,60416207185,fraud_Daugherty LLC,34.79,1,Fort Washakie,WY,82514,1645,Information systems manager,4f0c1a14e0aa7eb56a490780ef9268c5,...,False,False,False,True,False,False,False,False,False,False
2907,60416207185,fraud_Beier and Sons,27.18,1,Fort Washakie,WY,82514,1645,Information systems manager,3b2ebd3af508afba959640893e1e82bc,...,False,False,True,False,False,False,False,False,False,False

In [39]:
#now job column using frequency encoding, as 478 rows,if onehotencoding, then large space unnecessary
job_freq=df['job'].value_counts() #target encoding later
df['job'] = df['job'].map(job_freq)

In [40]:
df.head()

,cc_num,merchant,amt,gender,city,state,zip,city_pop,job,trans_num,...,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
1017,60416207185,"fraud_Jones, Sawayn and Romaguera",7.27,1,Fort Washakie,WY,82514,1645,2021,98e3dcf98101146a577f85a34e58feec,...,False,False,False,False,True,False,False,False,False,False
2724,60416207185,fraud_Berge LLC,52.94,1,Fort Washakie,WY,82514,1645,2021,498120fc45d277f7c88e3dba79c33865,...,False,False,False,False,False,False,False,False,False,False
2726,60416207185,fraud_Luettgen PLC,82.08,1,Fort Washakie,WY,82514,1645,2021,95f514bb993151347c7acdf8505c3d62,...,False,False,False,False,False,False,False,False,False,False
2882,60416207185,fraud_Daugherty LLC,34.79,1,Fort Washakie,WY,82514,1645,2021,4f0c1a14e0aa7eb56a490780ef9268c5,...,False,False,False,True,False,False,False,False,False,False
2907,60416207185,fraud_Beier and Sons,27.18,1,Fort Washakie,WY,82514,1645,2021,3b2ebd3af508afba959640893e1e82bc,...,False,False,True,False,False,False,False,False,False,False

In [41]:
df.head()

,cc_num,merchant,amt,gender,city,state,zip,city_pop,job,trans_num,...,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
1017,60416207185,"fraud_Jones, Sawayn and Romaguera",7.27,1,Fort Washakie,WY,82514,1645,2021,98e3dcf98101146a577f85a34e58feec,...,False,False,False,False,True,False,False,False,False,False
2724,60416207185,fraud_Berge LLC,52.94,1,Fort Washakie,WY,82514,1645,2021,498120fc45d277f7c88e3dba79c33865,...,False,False,False,False,False,False,False,False,False,False
2726,60416207185,fraud_Luettgen PLC,82.08,1,Fort Washakie,WY,82514,1645,2021,95f514bb993151347c7acdf8505c3d62,...,False,False,False,False,False,False,False,False,False,False
2882,60416207185,fraud_Daugherty LLC,34.79,1,Fort Washakie,WY,82514,1645,2021,4f0c1a14e0aa7eb56a490780ef9268c5,...,False,False,False,True,False,False,False,False,False,False
2907,60416207185,fraud_Beier and Sons,27.18,1,Fort Washakie,WY,82514,1645,2021,3b2ebd3af508afba959640893e1e82bc,...,False,False,True,False,False,False,False,False,False,False

In [42]:
merchant_freq = df['merchant'].value_counts()
df['merchant'] = df['merchant'].map(merchant_freq)

In [43]:
city_freq = df['city'].value_counts()
df['city'] = df['city'].map(city_freq)

In [44]:
df = pd.get_dummies(df, columns=['state'], drop_first=True, dtype=int)

In [45]:
df = df.drop(columns=['cc_num', 'trans_num'])

In [46]:
df.head()

,merchant,amt,gender,city,zip,city_pop,job,is_fraud,age,distance_km,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
1017,1269,7.27,1,3527,82514,1645,2021,0,40,127.606239,...,0,0,0,0,0,0,0,0,0,1
2724,2677,52.94,1,3527,82514,1645,2021,0,40,110.308921,...,0,0,0,0,0,0,0,0,0,1
2726,2630,82.08,1,3527,82514,1645,2021,0,40,21.787261,...,0,0,0,0,0,0,0,0,0,1
2882,2230,34.79,1,3527,82514,1645,2021,0,40,87.204215,...,0,0,0,0,0,0,0,0,0,1
2907,2473,27.18,1,3527,82514,1645,2021,0,40,74.212965,...,0,0,0,0,0,0,0,0,0,1

In [47]:
df.columns

Index(['merchant', 'amt', 'gender', 'city', 'zip', 'city_pop', 'job',
       'is_fraud', 'age', 'distance_km', 'time_diff', 'dist_diff', 'speed',
       'year', 'month', 'day', 'day_of_week', 'is_weekend',
       'category_food_dining', 'category_gas_transport',
       'category_grocery_net', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_misc_pos', 'category_personal_care',
       'category_shopping_net', 'category_shopping_pos', 'category_travel',
       'state_AL', 'state_AR', 'state_AZ', 'state_CA', 'state_CO', 'state_CT',
       'state_DC', 'state_DE', 'state_FL', 'state_GA', 'state_HI', 'state_IA',
       'state_ID', 'state_IL', 'state_IN', 'state_KS', 'state_KY', 'state_LA',
       'state_MA', 'state_MD', 'state_ME', 'state_MI', 'state_MN', 'state_MO',
       'state_MS', 'state_MT', 'state_NC', 'state_ND', 'state_NE', 'state_NH',
       'state_NJ', 'state_NM', 'state_NV', 'state_NY', 'state_OH', 'state_OK',
       'state_OR', 'state_PA', 'state_RI', 'state_SC', 'state_SD', 'state_TN',
       'state_TX', 'state_UT', 'state_VA', 'state_VT', 'state_WA', 'state_WI',
       'state_WV', 'state_WY'],
      dtype='object')

In [48]:
df = df.drop(columns=['zip'])

In [49]:
df['is_fraud'] = df['is_fraud'].astype(int)

In [50]:
df.select_dtypes(include='object')

Empty DataFrame
Columns: []
Index: [1017, 2724, 2726, 2882, 2907, 4135, 4337, 5467, 6027, 6273, 7473, 8351, 10739, 12714, 14329, 14342, 14749, 15355, 16787, 18158, 18264, 18668, 19025, 21577, 23567, 23658, 24895, 25419, 28322, 28630, 28631, 28894, 30243, 30711, 30898, 31392, 31598, 33390, 36962, 37491, 38808, 39722, 40156, 40268, 40410, 41509, 43067, 43250, 43662, 44399, 44717, 46894, 47046, 48782, 49081, 49109, 54762, 55345, 56174, 56308, 56912, 57433, 59150, 59653, 60539, 61723, 63957, 64582, 64861, 65783, 66788, 67016, 67770, 70285, 70984, 73234, 74568, 75963, 76019, 76412, 77856, 80070, 80511, 80563, 80737, 81764, 84371, 85558, 86695, 86984, 87994, 88256, 88550, 89361, 89456, 89546, 89572, 89642, 89848, 89897, ...]

[1296675 rows x 0 columns]

In [51]:
import numpy as np

df = df.replace([np.inf, -np.inf], 0)
df = df.fillna(0)

In [52]:
df

,merchant,amt,gender,city,city_pop,job,is_fraud,age,distance_km,time_diff,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
1017,1269,7.27,1,3527,1645,2021,0,40,127.606239,0.0,...,0,0,0,0,0,0,0,0,0,1
2724,2677,52.94,1,3527,1645,2021,0,40,110.308921,71862.0,...,0,0,0,0,0,0,0,0,0,1
2726,2630,82.08,1,3527,1645,2021,0,40,21.787261,159.0,...,0,0,0,0,0,0,0,0,0,1
2882,2230,34.79,1,3527,1645,2021,0,40,87.204215,13838.0,...,0,0,0,0,0,0,0,0,0,1
2907,2473,27.18,1,3527,1645,2021,0,40,74.212965,1952.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294934,1808,60.47,0,2059,532,6118,0,70,78.492562,30740.0,...,0,0,0,0,0,0,0,0,0,0
1295369,2639,74.29,0,2059,532,6118,0,70,55.400768,12962.0,...,0,0,0,0,0,0,0,0,0,0
1295587,1904,246.56,0,2059,532,6118,0,70,115.674400,7618.0,...,0,0,0,0,0,0,0,0,0,0
1296206,2306,2.62,0,2059,532,6118,0,70,60.513397,18989.0,...,0,0,0,0,0,0,0,0,0,0
1296427,2551,39.29,0,2059,532,6118,0,70,52.650493,6870.0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
X= df.drop(columns=['is_fraud'])
y=df['is_fraud']

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [55]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=20,   # ↓ reduce
    class_weight='balanced',
    random_state=42,
    n_jobs=-1          # 🔥 use all CPU cores
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=20, n_jobs=-1,
                       random_state=42)

In [56]:
y_prob = model.predict_proba(X_val)[:, 1]

y_pred_new = (y_prob > 0.2).astype(int)   # 🔥 lower threshold

In [58]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val, y_pred_new))

0.9972930765226444

In [59]:
from sklearn.metrics import classification_report

print(classification_report(y_val, y_pred_new))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    257834
           1       0.77      0.76      0.77      1501

    accuracy                           1.00    259335
   macro avg       0.88      0.88      0.88    259335
weighted avg       1.00      1.00      1.00    259335

In [118]:
df_test=pd.read_csv('fraudTest.csv')

In [119]:
df.head()

,merchant,amt,gender,city,city_pop,job,is_fraud,age,distance_km,time_diff,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
1017,1269,7.27,1,3527,1645,2021,0,40,127.606239,0.0,...,0,0,0,0,0,0,0,0,0,1
2724,2677,52.94,1,3527,1645,2021,0,40,110.308921,71862.0,...,0,0,0,0,0,0,0,0,0,1
2726,2630,82.08,1,3527,1645,2021,0,40,21.787261,159.0,...,0,0,0,0,0,0,0,0,0,1
2882,2230,34.79,1,3527,1645,2021,0,40,87.204215,13838.0,...,0,0,0,0,0,0,0,0,0,1
2907,2473,27.18,1,3527,1645,2021,0,40,74.212965,1952.0,...,0,0,0,0,0,0,0,0,0,1

In [120]:
df.columns

Index(['merchant', 'amt', 'gender', 'city', 'city_pop', 'job', 'is_fraud',
       'age', 'distance_km', 'time_diff', 'dist_diff', 'speed', 'year',
       'month', 'day', 'day_of_week', 'is_weekend', 'category_food_dining',
       'category_gas_transport', 'category_grocery_net',
       'category_grocery_pos', 'category_health_fitness', 'category_home',
       'category_kids_pets', 'category_misc_net', 'category_misc_pos',
       'category_personal_care', 'category_shopping_net',
       'category_shopping_pos', 'category_travel', 'state_AL', 'state_AR',
       'state_AZ', 'state_CA', 'state_CO', 'state_CT', 'state_DC', 'state_DE',
       'state_FL', 'state_GA', 'state_HI', 'state_IA', 'state_ID', 'state_IL',
       'state_IN', 'state_KS', 'state_KY', 'state_LA', 'state_MA', 'state_MD',
       'state_ME', 'state_MI', 'state_MN', 'state_MO', 'state_MS', 'state_MT',
       'state_NC', 'state_ND', 'state_NE', 'state_NH', 'state_NJ', 'state_NM',
       'state_NV', 'state_NY', 'state_OH', 'state_OK', 'state_OR', 'state_PA',
       'state_RI', 'state_SC', 'state_SD', 'state_TN', 'state_TX', 'state_UT',
       'state_VA', 'state_VT', 'state_WA', 'state_WI', 'state_WV', 'state_WY'],
      dtype='object')

In [121]:
df_test['dob'] = pd.to_datetime(df_test['dob'])
df_test['age'] = (pd.to_datetime('today') - df_test['dob']).dt.days // 365
df_test = df_test.drop(columns=['dob'])

In [122]:
df_test['trans_date_trans_time'] = pd.to_datetime(df_test['trans_date_trans_time'])

df_test['hour'] = df_test['trans_date_trans_time'].dt.hour
df_test['day'] = df_test['trans_date_trans_time'].dt.day
df_test['month'] = df_test['trans_date_trans_time'].dt.month
df_test['day_of_week'] = df_test['trans_date_trans_time'].dt.dayofweek
df_test['is_weekend'] = (df_test['day_of_week'] >= 5).astype(int)

df_test = df_test.drop(columns=['trans_date_trans_time'])

In [123]:
from geopy.distance import geodesic

df_test['distance_km'] = df_test.apply(
    lambda row: geodesic(
        (row['lat'], row['long']),
        (row['merch_lat'], row['merch_long'])
    ).km,
    axis=1
)

df_test = df_test.drop(columns=['lat','long','merch_lat','merch_long'])

In [124]:
df_test = df_test.sort_values(by=['cc_num','unix_time'])

df_test['time_diff'] = df_test.groupby('cc_num')['unix_time'].diff().abs()
df_test['dist_diff'] = df_test.groupby('cc_num')['distance_km'].diff().abs()

df_test['speed'] = df_test['dist_diff'] / (df_test['time_diff'] / 3600)

import numpy as np
df_test['speed'] = df_test['speed'].replace([np.inf, -np.inf], 0)
df_test['speed'] = df_test['speed'].fillna(0)

In [125]:
df_test = df_test.drop(columns=[
    'first','last','street','trans_num','cc_num','unix_time'
])

In [126]:
df_test['gender'] = df_test['gender'].map({'M':0, 'F':1})

In [127]:
#reuse from train dataset    .map( )
df_test['merchant'] = df_test['merchant'].map(merchant_freq)
df_test['city'] = df_test['city'].map(city_freq)
df_test['job'] = df_test['job'].map(job_freq)

In [128]:
df_test = pd.get_dummies(df_test, columns=['category'], drop_first=True, dtype=int)
df_test = pd.get_dummies(df_test, columns=['state'], drop_first=True, dtype=int)

In [129]:
df_test = df_test.drop(columns=['zip'])

In [130]:
df_test = df_test.replace([np.inf, -np.inf], 0)
df_test = df_test.fillna(0)

In [131]:
y_test = df_test['is_fraud']

In [132]:
df_test = df_test.reindex(columns=X.columns, fill_value=0)

In [133]:
df_test

,merchant,amt,gender,city,city_pop,job,age,distance_km,time_diff,dist_diff,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
157,2391,124.66,1,3527.0,1645,2021.0,40,30.533617,0.0,0.000000,...,0,0,0,0,0,0,0,0,0,1
741,1597,78.52,1,3527.0,1645,2021.0,40,91.864216,11994.0,61.330599,...,0,0,0,0,0,0,0,0,0,1
3047,2603,65.25,1,3527.0,1645,2021.0,40,121.877934,55977.0,30.013718,...,0,0,0,0,0,0,0,0,0,1
4351,2244,87.74,1,3527.0,1645,2021.0,40,65.393092,27238.0,56.484842,...,0,0,0,0,0,0,0,0,0,1
7695,1851,148.02,1,3527.0,1645,2021.0,40,38.394780,75383.0,26.998311,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552584,2637,66.11,0,2059.0,532,6118.0,70,44.930513,8077.0,37.020739,...,0,0,0,0,0,0,0,0,0,0
552892,1291,4.58,0,2059.0,532,6118.0,70,81.527378,11005.0,36.596864,...,0,0,0,0,0,0,0,0,0,0
553559,2705,95.96,0,2059.0,532,6118.0,70,36.017775,21729.0,45.509602,...,0,0,0,0,0,0,0,0,0,0
553560,2420,149.48,0,2059.0,532,6118.0,70,81.940542,101.0,45.922767,...,0,0,0,0,0,0,0,0,0,0
553883,2199,20.55,0,2059.0,532,6118.0,70,22.092692,7631.0,59.847850,...,0,0,0,0,0,0,0,0,0,0

In [134]:
X_test = df_test

In [135]:
y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob > 0.2).astype(int)

In [136]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[552922    652]
 [   669   1476]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.69      0.69      0.69      2145

    accuracy                           1.00    555719
   macro avg       0.85      0.84      0.84    555719
weighted avg       1.00      1.00      1.00    555719

In [137]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9976228993430133